# Generated by Django 3.0.3 on 2020-09-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchbar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='co_work_nums',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='actor',
            name='movies_name_str',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='actor',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors_name_str',
            field=models.CharField(default='', max_length=500),
        ),
    ]
